// Chemical database - Lukas Horticulture App
// 97 unique chemicals (100 - 3 duplicates: C066/Pylon, C068/Ventigra, C080/Avid)
// All fields complete and uniform
// Generated: 2025-11-24

const chemicals = [
  {
    "id": "C001",
    "name": "PIN-DEE 3.3 T&O Herbicide",
    "category": "Herbicide - Pre-emergent",
    "type": "Concentrate",
    "actives": "Pendimethalin 37.4%",
    "moa": "WSSA 3",
    "rei": "0.5 to 12 hours",
    "mixRate": "1.8\u20133.6 fl oz (covers ~1,000 sq ft)",
    "targetSpectrum": "Broad spectrum weed control",
    "targetTypes": "Weeds",
    "allowedSites": "Ornamentals, nursery beds (not edible crops)",
    "restrictions": "Avoid drift; follow REI; no food crops",
    "ipmCategory": "Herbicide",
    "notes": "Refer to product label for complete information",
    "manufacturer": "Drexel Chemical Company",
    "epaRegNum": "19713-590",
    "epaLabelUrl": "https://labelsds.com/images/user_uploads/Pin%20Dee%203.3%20TO%20Label%207-1-12.pdf",
    "moaName": "Herbicide MOA",
    "moaDescription": "Prevents weed germination",
    "systemic": "Soil-residual",
    "appType": "Pre-emergent spray",
    "defaultRatePerGallon": 1.8
  },
  {
    "id": "C002",
    "name": "Pendulum AquaCap",
    "category": "Herbicide - Pre-emergent",
    "type": "Concentrate (microencapsulated)",
    "actives": "Pendimethalin 38.7%",
    "moa": "WSSA 3",
    "rei": "12.0",
    "mixRate": "Label-dependent (pre-emergent barrier)",
    "targetSpectrum": "Nursery weeds (grasses & some broadleaves)",
    "targetTypes": "Weeds",
    "allowedSites": "Turf, ornamentals",
    "restrictions": "Do NOT mix with acidifiers; avoid aquatic areas",
    "ipmCategory": "Herbicide",
    "notes": "Avoid low pH adjuvants that can break capsules.",
    "manufacturer": "BASF Corporation",
    "epaRegNum": "241-416",
    "epaLabelUrl": "https://labelsds.com/images/user_uploads/Pendulum%20Aquacap%20Label%207-2-20.pdf",
    "moaName": "Dinitroaniline",
    "moaDescription": "Pre-emergent root inhibition",
    "systemic": "Soil-residual",
    "appType": "Soil pre-emergent",
    "defaultRatePerGallon": null
  },
  {
    "id": "C003",
    "name": "Snapshot 2.5 TG",
    "category": "Herbicide - Pre-emergent",
    "type": "Granular",
    "actives": "Trifluralin + Isoxaben",
    "moa": "WSSA 3 + 29",
    "rei": "0.5 to 12 hours",
    "mixRate": "N/A (granular product)",
    "targetSpectrum": "Broad spectrum weed control",
    "targetTypes": "Weeds",
    "allowedSites": "Ornamental beds, container plants",
    "restrictions": "Granular only; do not spray; avoid young plant crowns",
    "ipmCategory": "Herbicide",
    "notes": "Applied by weight over area, not as spray solution.",
    "manufacturer": "Corteva Agriscience",
    "epaRegNum": "62719-175",
    "epaLabelUrl": "https://www.domyown.com/snapshot-25-tg-50-lbs-p-1337.html",
    "moaName": "Herbicide MOA",
    "moaDescription": "Prevents weed germination",
    "systemic": "Soil-residual",
    "appType": "Granular application",
    "defaultGranularRatePerThousandSqFt": 3.5,
    "defaultRatePerGallon": null
  },
  {
    "id": "C004",
    "name": "Biathlon Ornamental Herbicide",
    "category": "Herbicide - Pre-emergent",
    "type": "Granular",
    "actives": "Oxyfluorfen + Prodiamine",
    "moa": "WSSA 14 + 3",
    "rei": "0.5 to 12 hours",
    "mixRate": "N/A (granular product)",
    "targetSpectrum": "Broad spectrum weed control",
    "targetTypes": "Weeds",
    "allowedSites": "Ornamentals, nursery beds",
    "restrictions": "Granular only; avoid exposed roots",
    "ipmCategory": "Herbicide",
    "notes": "Refer to product label for complete information",
    "manufacturer": "OHP, Inc.",
    "epaRegNum": "59807-12",
    "epaLabelUrl": "https://domyown.com/ohp-biathlon-ornamental-herbicide-p-10215.html",
    "moaName": "Herbicide MOA",
    "moaDescription": "Prevents weed germination",
    "systemic": "Soil-residual",
    "appType": "Granular application",
    "defaultGranularRatePerThousandSqFt": 2.3,
    "defaultRatePerGallon": null
  },
  {
    "id": "C005",
    "name": "Fortress Ornamental Herbicide",
    "category": "Herbicide - Pre-emergent",
    "type": "Granular",
    "actives": "Isoxaben + Dithiopyr",
    "moa": "WSSA 29 + 3",
    "rei": "0.5 to 12 hours",
    "mixRate": "N/A (granular product)",
    "targetSpectrum": "Broad spectrum weed control",
    "targetTypes": "Weeds",
    "allowedSites": "Ornamental nursery beds",
    "restrictions": "Not for turf; avoid greenhouse interiors",
    "ipmCategory": "Herbicide",
    "notes": "Refer to product label for complete information",
    "manufacturer": "OHP, Inc.",
    "epaRegNum": "59807-19",
    "epaLabelUrl": "https://www.ohp.com/Products/fortress.php",
    "moaName": "Herbicide MOA",
    "moaDescription": "Prevents weed germination",
    "systemic": "Soil-residual",
    "appType": "Granular application",
    "defaultGranularRatePerThousandSqFt": 3.4,
    "defaultRatePerGallon": null
  },
  {
    "id": "C006",
    "name": "Drive XLR8",
    "category": "Herbicide - Post-emergent (turf)",
    "type": "Concentrate",
    "actives": "Quinclorac",
    "moa": "WSSA 4",
    "rei": "0.5 to 12 hours",
    "mixRate": "\u22480.55 fl oz",
    "targetSpectrum": "Broad spectrum weed control",
    "targetTypes": "Weeds",
    "allowedSites": "Turf only",
    "restrictions": "Not for ornamentals; REI 12 hr",
    "ipmCategory": "Herbicide",
    "notes": "Check label for turf species and max annual rates.",
    "manufacturer": "UNKNOWN",
    "epaRegNum": "TBD",
    "epaLabelUrl": "TBD",
    "moaName": "Herbicide MOA",
    "moaDescription": "Controls emerged weeds",
    "systemic": "Contact",
    "appType": "Post-emergent spray",
    "defaultRatePerGallon": 0.55
  },
  {
    "id": "C007",
    "name": "Hi-Yield Grass Killer",
    "category": "Herbicide - Post-emergent (grass-selective)",
    "type": "Concentrate",
    "actives": "Sethoxydim 18%",
    "moa": "WSSA 1",
    "rei": "0.5 to 12 hours",
    "mixRate": "\u22482\u20133 fl oz",
    "targetSpectrum": "Broad spectrum weed control",
    "targetTypes": "Weeds",
    "allowedSites": "Ornamental beds, shrubs",
    "restrictions": "Not for turf; do not tank-mix with 2,4-D",
    "ipmCategory": "Herbicide",
    "notes": "Do not tank mix with 2,4-D/dicamba products.",
    "manufacturer": "UNKNOWN",
    "epaRegNum": "TBD",
    "epaLabelUrl": "TBD",
    "moaName": "Herbicide MOA",
    "moaDescription": "Controls emerged weeds",
    "systemic": "Contact",
    "appType": "Post-emergent spray",
    "defaultRatePerGallon": 2.0
  },
  {
    "id": "C008",
    "name": "Ferti-lome Weed-Out with Crabgrass Killer",
    "category": "Herbicide - Post-emergent (broadleaf + grassy)",
    "type": "Concentrate",
    "actives": "2,4-D + Quinclorac + Dicamba",
    "moa": "WSSA 4",
    "rei": "0.5 to 12 hours",
    "mixRate": "\u22481.5 fl oz",
    "targetSpectrum": "Broad spectrum weed control",
    "targetTypes": "Weeds",
    "allowedSites": "Turf only",
    "restrictions": "Drift-sensitive; not for ornamentals",
    "ipmCategory": "Herbicide",
    "notes": "Lawn/turf use; observe buffer zones and drift precautions.",
    "manufacturer": "UNKNOWN",
    "epaRegNum": "TBD",
    "epaLabelUrl": "TBD",
    "moaName": "Herbicide MOA",
    "moaDescription": "Controls emerged weeds",
    "systemic": "Contact",
    "appType": "Post-emergent spray",
    "defaultRatePerGallon": 1.5
  },
  {
    "id": "C009",
    "name": "Roundup Pro Concentrate",
    "category": "Herbicide - Non-selective systemic",
    "type": "Concentrate",
    "actives": "Glyphosate 50.2%",
    "moa": "WSSA 9",
    "rei": "0.5 to 12 hours",
    "mixRate": "\u22481.5\u20134 fl oz (depends on weed size)",
    "targetSpectrum": "Broad spectrum weed control",
    "targetTypes": "Weeds",
    "allowedSites": "See product label",
    "restrictions": "Follow all label instructions and local regulations",
    "ipmCategory": "Herbicide",
    "notes": "Avoid mixing with contact herbicides like diquat.",
    "manufacturer": "Check product label",
    "epaRegNum": "See product label",
    "epaLabelUrl": "Check EPA website",
    "moaName": "Herbicide MOA",
    "moaDescription": "Pest management control",
    "systemic": "Contact",
    "appType": "Spray application",
    "defaultRatePerGallon": 1.5
  },
  {
    "id": "C010",
    "name": "Martin's Eraser A/P",
    "category": "Herbicide - Non-selective systemic",
    "type": "Concentrate",
    "actives": "Glyphosate 41%",
    "moa": "WSSA 9",
    "rei": "0.5 to 12 hours",
    "mixRate": "\u22482\u20134 fl oz",
    "targetSpectrum": "Broad spectrum weed control",
    "targetTypes": "Weeds",
    "allowedSites": "Non-selective turf/ornamental areas",
    "restrictions": "Same as glyphosate; avoid drift",
    "ipmCategory": "Herbicide",
    "notes": "Refer to product label for complete information",
    "manufacturer": "Check product label",
    "epaRegNum": "See product label",
    "epaLabelUrl": "Check EPA website",
    "moaName": "Herbicide MOA",
    "moaDescription": "Pest management control",
    "systemic": "Contact",
    "appType": "Spray application",
    "defaultRatePerGallon": 2.0
  },
  {
    "id": "C011",
    "name": "Remedy",
    "category": "Herbicide - Brush/woody plant",
    "type": "Concentrate (ester)",
    "actives": "Triclopyr butoxyethyl ester",
    "moa": "WSSA 4",
    "rei": "0.5 to 12 hours",
    "mixRate": "\u22481\u20134 fl oz (brush control)",
    "targetSpectrum": "Broad spectrum weed control",
    "targetTypes": "Weeds",
    "allowedSites": "Brush/woody vegetation (non-nursery)",
    "restrictions": "Ester volatility; keep away from ornamentals",
    "ipmCategory": "Herbicide",
    "notes": "Refer to product label for complete information",
    "manufacturer": "Check product label",
    "epaRegNum": "See product label",
    "epaLabelUrl": "Check EPA website",
    "moaName": "Herbicide MOA",
    "moaDescription": "Pest management control",
    "systemic": "Contact",
    "appType": "Spray application",
    "defaultRatePerGallon": 1.0
  },
  {
    "id": "C012",
    "name": "Garlon 3A",
    "category": "Herbicide - Brush/woody plant",
    "type": "Concentrate (amine)",
    "actives": "Triclopyr amine",
    "moa": "WSSA 4",
    "rei": "0.5 to 12 hours",
    "mixRate": "Label-dependent (foliar/brush rates)",
    "targetSpectrum": "Broad spectrum weed control",
    "targetTypes": "Weeds",
    "allowedSites": "Brush, forestry, limited ornamental uses",
    "restrictions": "Check site before use; avoid greenhouse interiors",
    "ipmCategory": "Herbicide",
    "notes": "Refer to product label for complete information",
    "manufacturer": "Check product label",
    "epaRegNum": "See product label",
    "epaLabelUrl": "Check EPA website",
    "moaName": "Herbicide MOA",
    "moaDescription": "Pest management control",
    "systemic": "Contact",
    "appType": "Spray application",
    "defaultRatePerGallon": null
  },
  {
    "id": "C013",
    "name": "Bonide Sedge Ender",
    "category": "Herbicide - Sedges & grassy weeds",
    "type": "Concentrate",
    "actives": "Sulfentrazone + Prodiamine",
    "moa": "WSSA 14 + 3",
    "rei": "0.5 to 12 hours",
    "mixRate": "\u22482\u20134 fl oz",
    "targetSpectrum": "Broad spectrum weed control",
    "targetTypes": "Weeds",
    "allowedSites": "Turf, some ornamentals",
    "restrictions": "Check species sensitivity",
    "ipmCategory": "Herbicide",
    "notes": "Refer to product label for complete information",
    "manufacturer": "Check product label",
    "epaRegNum": "See product label",
    "epaLabelUrl": "Check EPA website",
    "moaName": "Herbicide MOA",
    "moaDescription": "Pest management control",
    "systemic": "Contact",
    "appType": "Spray application",
    "defaultRatePerGallon": 2.0
  },
  {
    "id": "C014",
    "name": "Reward Herbicide",
    "category": "Herbicide - Contact / aquatic & terrestrial",
    "type": "Concentrate",
    "actives": "Diquat dibromide 37.3%",
    "moa": "WSSA 22",
    "rei": "0.5 to 12 hours",
    "mixRate": "\u22480.75\u20131.5 fl oz",
    "targetSpectrum": "Broad spectrum weed control",
    "targetTypes": "Weeds",
    "allowedSites": "Aquatic + ornamentals (depending on label)",
    "restrictions": "Never mix with glyphosate or Sonar",
    "ipmCategory": "Herbicide",
    "notes": "Do not mix with glyphosate when systemic activity is desired.",
    "manufacturer": "Check product label",
    "epaRegNum": "See product label",
    "epaLabelUrl": "Check EPA website",
    "moaName": "Herbicide MOA",
    "moaDescription": "Pest management control",
    "systemic": "Contact",
    "appType": "Spray application",
    "defaultRatePerGallon": 0.75
  },
  {
    "id": "C015",
    "name": "Sonar RTU",
    "category": "Herbicide - Aquatic systemic",
    "type": "RTU",
    "actives": "Fluridone",
    "moa": "WSSA 12",
    "rei": "0.5 to 12 hours",
    "mixRate": "RTU (no dilution)",
    "targetSpectrum": "Broad spectrum weed control",
    "targetTypes": "Weeds",
    "allowedSites": "Aquatic systems",
    "restrictions": "Do not mix with copper or diquat; long residual",
    "ipmCategory": "Herbicide",
    "notes": "Refer to product label for complete information",
    "manufacturer": "Check product label",
    "epaRegNum": "See product label",
    "epaLabelUrl": "Check EPA website",
    "moaName": "Herbicide MOA",
    "moaDescription": "Pest management control",
    "systemic": "Contact",
    "appType": "Spray application",
    "defaultRatePerGallon": null
  },
  {
    "id": "C016",
    "name": "Monterey Fruit Tree & Vegetable Systemic Soil Drench",
    "category": "Insecticide - Systemic soil drench",
    "type": "Concentrate",
    "actives": "Imidacloprid",
    "moa": "IRAC 4A",
    "rei": "12 to 24 hours",
    "mixRate": "\u22480.25\u20130.5 fl oz",
    "targetSpectrum": "Insect pest control",
    "targetTypes": "Insects",
    "allowedSites": "See product label",
    "restrictions": "Follow all label instructions and local regulations",
    "ipmCategory": "Insecticide",
    "notes": "Refer to product label for complete information",
    "manufacturer": "Check product label",
    "epaRegNum": "See product label",
    "epaLabelUrl": "Check EPA website",
    "moaName": "Insecticide MOA",
    "moaDescription": "Pest management control",
    "systemic": "Soil-residual",
    "appType": "Spray application",
    "defaultRatePerGallon": 0.25
  },
  {
    "id": "C017",
    "name": "TriStar 8.5 SL",
    "category": "Insecticide - Systemic",
    "type": "Concentrate",
    "actives": "Acetamiprid 8.5%",
    "moa": "IRAC 4A",
    "rei": "12 to 24 hours",
    "mixRate": "\u22480.2\u20130.6 fl oz",
    "targetSpectrum": "Insect pest control",
    "targetTypes": "Insects",
    "allowedSites": "Greenhouse, nursery, ornamentals",
    "restrictions": "None beyond label",
    "ipmCategory": "Insecticide",
    "notes": "Refer to product label for complete information",
    "manufacturer": "Check product label",
    "epaRegNum": "See product label",
    "epaLabelUrl": "Check EPA website",
    "moaName": "Insecticide MOA",
    "moaDescription": "Pest management control",
    "systemic": "Contact",
    "appType": "Spray application",
    "defaultRatePerGallon": 0.2
  },
  {
    "id": "C018",
    "name": "Bonide Systemic Insect Control",
    "category": "Insecticide - Systemic",
    "type": "Concentrate",
    "actives": "Acephate 9.4%",
    "moa": "IRAC 1B",
    "rei": "12 to 24 hours",
    "mixRate": "\u22481 fl oz (per prior calc: 1 pint \u2192 16 gal)",
    "targetSpectrum": "Insect pest control",
    "targetTypes": "Insects",
    "allowedSites": "Ornamentals",
    "restrictions": "Odor complaints; avoid enclosed areas",
    "ipmCategory": "Insecticide",
    "notes": "Refer to product label for complete information",
    "manufacturer": "Check product label",
    "epaRegNum": "See product label",
    "epaLabelUrl": "Check EPA website",
    "moaName": "Insecticide MOA",
    "moaDescription": "Pest management control",
    "systemic": "Contact",
    "appType": "Spray application",
    "defaultRatePerGallon": 1.0
  },
  {
    "id": "C019",
    "name": "Ortho Tree & Shrub Insect Control Granules",
    "category": "Insecticide - Systemic granular",
    "type": "Granular",
    "actives": "Imidacloprid 0.2%",
    "moa": "IRAC 4A",
    "rei": "12 to 24 hours",
    "mixRate": "N/A (granular)",
    "targetSpectrum": "Insect pest control",
    "targetTypes": "Insects",
    "allowedSites": "Ornamentals",
    "restrictions": "Soil-only granules; not for food crops",
    "ipmCategory": "Insecticide",
    "notes": "Refer to product label for complete information",
    "manufacturer": "Check product label",
    "epaRegNum": "See product label",
    "epaLabelUrl": "Check EPA website",
    "moaName": "Insecticide MOA",
    "moaDescription": "Pest management control",
    "systemic": "Systemic",
    "appType": "Granular application",
    "defaultRatePerGallon": null
  },
  {
    "id": "C020",
    "name": "Hi-Yield Bug Blaster II RTS",
    "category": "Insecticide - Contact",
    "type": "RTS",
    "actives": "Bifenthrin 2.4%",
    "moa": "IRAC 3A",
    "rei": "12 to 24 hours",
    "mixRate": "RTS (no dilution)",
    "targetSpectrum": "Insect pest control",
    "targetTypes": "Insects",
    "allowedSites": "Turf, ornamentals",
    "restrictions": "Highly toxic to fish; avoid waterways",
    "ipmCategory": "Insecticide",
    "notes": "Refer to product label for complete information",
    "manufacturer": "Check product label",
    "epaRegNum": "See product label",
    "epaLabelUrl": "Check EPA website",
    "moaName": "Insecticide MOA",
    "moaDescription": "Pest management control",
    "systemic": "Contact",
    "appType": "Ready-to-spray",
    "defaultRatePerGallon": null
  },
  {
    "id": "C021",
    "name": "Martin's Cyonara Lawn & Garden RTS",
    "category": "Insecticide - Contact",
    "type": "RTS",
    "actives": "Lambda-cyhalothrin 0.5%",
    "moa": "IRAC 3A",
    "rei": "12 to 24 hours",
    "mixRate": "RTS (no dilution)",
    "targetSpectrum": "Insect pest control",
    "targetTypes": "Insects",
    "allowedSites": "Turf, ornamentals",
    "restrictions": "Avoid water; drift restrictions",
    "ipmCategory": "Insecticide",
    "notes": "Refer to product label for complete information",
    "manufacturer": "Check product label",
    "epaRegNum": "See product label",
    "epaLabelUrl": "Check EPA website",
    "moaName": "Insecticide MOA",
    "moaDescription": "Pest management control",
    "systemic": "Contact",
    "appType": "Ready-to-spray",
    "defaultRatePerGallon": null
  },
  {
    "id": "C022",
    "name": "Ferti-lome Liquid Systemic Fungicide II",
    "category": "Fungicide - Systemic",
    "type": "Concentrate",
    "actives": "Propiconazole 1.55%",
    "moa": "FRAC 3",
    "rei": "12 to 24 hours",
    "mixRate": "1 fl oz",
    "targetSpectrum": "Fungal disease control",
    "targetTypes": "Fungi",
    "allowedSites": "Turf + ornamentals (if labeled)",
    "restrictions": "Ensure product version is labeled for ornamentals",
    "ipmCategory": "Fungicide",
    "notes": "Refer to product label for complete information",
    "manufacturer": "Check product label",
    "epaRegNum": "See product label",
    "epaLabelUrl": "Check EPA website",
    "moaName": "Fungicide MOA",
    "moaDescription": "Pest management control",
    "systemic": "Contact",
    "appType": "Spray application",
    "defaultRatePerGallon": 1.0
  },
  {
    "id": "C023",
    "name": "Conserve SC",
    "category": "Insecticide (listed earlier but often used like a specialty product)",
    "type": "Concentrate",
    "actives": "Spinosad 11.6%",
    "moa": "IRAC 5",
    "rei": "4.0",
    "mixRate": "0.05 fl oz (\u22481.5 mL)",
    "targetSpectrum": "Thrips",
    "targetTypes": "Insect (thysanoptera)",
    "allowedSites": "See product label",
    "restrictions": "Follow all label instructions and local regulations",
    "ipmCategory": "Insecticide",
    "notes": "Refer to product label for complete information",
    "manufacturer": "Check product label",
    "epaRegNum": "See product label",
    "epaLabelUrl": "Check EPA website",
    "moaName": "Spinosyn",
    "moaDescription": "Nicotinic acetylcholine receptor modulator with GABA effects",
    "systemic": "Contact/Ingestion",
    "appType": "Foliar",
    "defaultRatePerGallon": 0.05
  },
  {
    "id": "C024",
    "name": "3336 F Fungicide",
    "category": "Fungicide - Systemic",
    "type": "Concentrate",
    "actives": "Thiophanate-methyl 41.25%",
    "moa": "FRAC 1",
    "rei": "12 to 24 hours",
    "mixRate": "\u22480.5\u20131.5 fl oz",
    "targetSpectrum": "Fungal disease control",
    "targetTypes": "Fungi",
    "allowedSites": "Ornamentals, greenhouse, turf",
    "restrictions": "Rotate FRAC groups to avoid resistance",
    "ipmCategory": "Fungicide",
    "notes": "High resistance risk; rotate FRAC groups.",
    "manufacturer": "Check product label",
    "epaRegNum": "See product label",
    "epaLabelUrl": "Check EPA website",
    "moaName": "Fungicide MOA",
    "moaDescription": "Pest management control",
    "systemic": "Contact",
    "appType": "Spray application",
    "defaultRatePerGallon": 0.5
  },
  {
    "id": "C025",
    "name": "Ferti-lome Copper Fungicide RTS",
    "category": "Fungicide - Protectant",
    "type": "RTS",
    "actives": "Copper octanoate (copper soap)",
    "moa": "FRAC M1",
    "rei": "12 to 24 hours",
    "mixRate": "RTS (no dilution)",
    "targetSpectrum": "Fungal disease control",
    "targetTypes": "Fungi",
    "allowedSites": "Ornamentals",
    "restrictions": "Not aquatic-approved",
    "ipmCategory": "Fungicide",
    "notes": "Refer to product label for complete information",
    "manufacturer": "Check product label",
    "epaRegNum": "See product label",
    "epaLabelUrl": "Check EPA website",
    "moaName": "Fungicide MOA",
    "moaDescription": "Pest management control",
    "systemic": "Contact",
    "appType": "Ready-to-spray",
    "defaultRatePerGallon": null
  },
  {
    "id": "C026",
    "name": "GreenClean Pro",
    "category": "Algaecide / Biocide",
    "type": "Granular / powder",
    "actives": "Sodium carbonate peroxyhydrate",
    "moa": "Oxidizer (non-classified)",
    "rei": "Consult label",
    "mixRate": "Label-dependent; often per surface area",
    "targetSpectrum": "Multi-purpose",
    "targetTypes": "Pests",
    "allowedSites": "Surfaces, algae, ornamental features",
    "restrictions": "Never tank-mix with pesticides",
    "ipmCategory": "Other",
    "notes": "Do not mix with pesticides in tank; oxidative.",
    "manufacturer": "Check product label",
    "epaRegNum": "See product label",
    "epaLabelUrl": "Check EPA website",
    "moaName": "See MOA Code",
    "moaDescription": "Pest management control",
    "systemic": "Systemic",
    "appType": "Granular application",
    "defaultGranularRatePerThousandSqFt": 2.0,
    "defaultRatePerGallon": null
  },
  {
    "id": "C027",
    "name": "Crystal Plex",
    "category": "Algaecide - Aquatic",
    "type": "Liquid",
    "actives": "Copper sulfate",
    "moa": "FRAC M1",
    "rei": "Consult label",
    "mixRate": "Label-dependent (aquatic use)",
    "targetSpectrum": "Multi-purpose",
    "targetTypes": "Pests",
    "allowedSites": "Aquatic systems",
    "restrictions": "Follow strict dosage; fish sensitivity",
    "ipmCategory": "Other",
    "notes": "Refer to product label for complete information",
    "manufacturer": "Check product label",
    "epaRegNum": "See product label",
    "epaLabelUrl": "Check EPA website",
    "moaName": "Fungicide MOA",
    "moaDescription": "Pest management control",
    "systemic": "Contact",
    "appType": "Spray application",
    "defaultRatePerGallon": null
  },
  {
    "id": "C028",
    "name": "Brandt Indicate 5",
    "category": "Adjuvant - pH adjuster / wetter",
    "type": "Liquid",
    "actives": "Acidifier + non-ionic surfactant blend",
    "moa": "",
    "rei": "Consult label",
    "mixRate": "\u22480.25\u20131 fl oz",
    "targetSpectrum": "Multi-purpose",
    "targetTypes": "Pests",
    "allowedSites": "Adjuvant for most pesticide uses",
    "restrictions": "Do NOT mix with Pendulum AquaCap",
    "ipmCategory": "Other",
    "notes": "Do not use with microencapsulated pendimethalin (AquaCap).",
    "manufacturer": "Check product label",
    "epaRegNum": "See product label",
    "epaLabelUrl": "Check EPA website",
    "moaName": "Not classified",
    "moaDescription": "Pest management control",
    "systemic": "Contact",
    "appType": "Spray application",
    "defaultRatePerGallon": 0.25
  },
  {
    "id": "C029",
    "name": "Liquid Fence Deer & Rabbit Repellent RTU",
    "category": "Repellent",
    "type": "RTU",
    "actives": "Putrescent egg solids + garlic, etc.",
    "moa": "",
    "rei": "Consult label",
    "mixRate": "RTU (no dilution)",
    "targetSpectrum": "Multi-purpose",
    "targetTypes": "Pests",
    "allowedSites": "Landscapes, ornamentals",
    "restrictions": "Not regulated as a pesticide; no EPA number",
    "ipmCategory": "Other",
    "notes": "Not a pesticide; no MOA code.",
    "manufacturer": "Check product label",
    "epaRegNum": "See product label",
    "epaLabelUrl": "Check EPA website",
    "moaName": "Not classified",
    "moaDescription": "Pest management control",
    "systemic": "Contact",
    "appType": "Spray application",
    "defaultRatePerGallon": null
  },
  {
    "id": "C030",
    "name": "Orkestra Intrinsic",
    "category": "Fungicide",
    "type": "Concentrate",
    "actives": "Fluxapyroxad + Pyraclostrobin",
    "moa": "7+11",
    "rei": "12.0",
    "mixRate": "See product label",
    "targetSpectrum": "Botrytis blight, Leaf spots / powdery mildew / rust, Root and crown rots (Fusarium, Rhizoctonia, Cylindrocladium, Thielaviopsis)",
    "targetTypes": "Fungal disease, Fungal disease complex, Soil-borne fungi",
    "allowedSites": "See product label",
    "restrictions": "Follow all label instructions and local regulations",
    "ipmCategory": "Fungicide",
    "notes": "Refer to product label for complete information",
    "manufacturer": "Check product label",
    "epaRegNum": "See product label",
    "epaLabelUrl": "Check EPA website",
    "moaName": "SDHI + QoI",
    "moaDescription": "Respiration inhibitors at mitochondrial Complex II and III",
    "systemic": "Systemic",
    "appType": "Foliar",
    "defaultRatePerGallon": null
  },
  {
    "id": "C031",
    "name": "Decree",
    "category": "Fungicide",
    "type": "Concentrate",
    "actives": "Fenhexamid",
    "moa": "17",
    "rei": "12.0",
    "mixRate": "See product label",
    "targetSpectrum": "Botrytis blight",
    "targetTypes": "Fungal disease",
    "allowedSites": "See product label",
    "restrictions": "Follow all label instructions and local regulations",
    "ipmCategory": "Fungicide",
    "notes": "Refer to product label for complete information",
    "manufacturer": "Check product label",
    "epaRegNum": "See product label",
    "epaLabelUrl": "Check EPA website",
    "moaName": "Hydroxyanilide",
    "moaDescription": "Sterol biosynthesis inhibitor with Botrytis specificity",
    "systemic": "Contact",
    "appType": "Foliar",
    "defaultRatePerGallon": null
  },
  {
    "id": "C032",
    "name": "Palladium",
    "category": "Fungicide",
    "type": "Concentrate",
    "actives": "Cyprodinil + Fludioxonil",
    "moa": "9+12",
    "rei": "12.0",
    "mixRate": "See product label",
    "targetSpectrum": "Botrytis blight",
    "targetTypes": "Fungal disease",
    "allowedSites": "See product label",
    "restrictions": "Follow all label instructions and local regulations",
    "ipmCategory": "Fungicide",
    "notes": "Refer to product label for complete information",
    "manufacturer": "Check product label",
    "epaRegNum": "See product label",
    "epaLabelUrl": "Check EPA website",
    "moaName": "AP + Phenylpyrrole",
    "moaDescription": "Protein synthesis disruption plus osmotic signal disruption",
    "systemic": "Contact",
    "appType": "Foliar",
    "defaultRatePerGallon": null
  },
  {
    "id": "C033",
    "name": "Affirm WDG",
    "category": "Fungicide",
    "type": "Concentrate",
    "actives": "Polyoxin-D zinc salt",
    "moa": "19",
    "rei": "12.0",
    "mixRate": "See product label",
    "targetSpectrum": "Botrytis blight",
    "targetTypes": "Fungal disease",
    "allowedSites": "See product label",
    "restrictions": "Follow all label instructions and local regulations",
    "ipmCategory": "Fungicide",
    "notes": "Refer to product label for complete information",
    "manufacturer": "Check product label",
    "epaRegNum": "See product label",
    "epaLabelUrl": "Check EPA website",
    "moaName": "Polyoxin",
    "moaDescription": "Inhibits chitin synthase and fungal cell wall formation",
    "systemic": "Contact",
    "appType": "Foliar",
    "defaultRatePerGallon": null
  },
  {
    "id": "C034",
    "name": "Astun SC",
    "category": "Fungicide",
    "type": "Concentrate",
    "actives": "Isofetamid",
    "moa": "7",
    "rei": "12.0",
    "mixRate": "See product label",
    "targetSpectrum": "Botrytis blight",
    "targetTypes": "Fungal disease",
    "allowedSites": "See product label",
    "restrictions": "Follow all label instructions and local regulations",
    "ipmCategory": "Fungicide",
    "notes": "Refer to product label for complete information",
    "manufacturer": "Check product label",
    "epaRegNum": "See product label",
    "epaLabelUrl": "Check EPA website",
    "moaName": "SDHI",
    "moaDescription": "Succinate dehydrogenase inhibitor; blocks respiration",
    "systemic": "Systemic",
    "appType": "Foliar",
    "defaultRatePerGallon": null
  },
  {
    "id": "C035",
    "name": "Protect DF",
    "category": "Fungicide",
    "type": "Concentrate",
    "actives": "Chlorothalonil",
    "moa": "M5",
    "rei": "12.0",
    "mixRate": "See product label",
    "targetSpectrum": "Leaf spots / powdery mildew / rust",
    "targetTypes": "Fungal disease complex",
    "allowedSites": "See product label",
    "restrictions": "Follow all label instructions and local regulations",
    "ipmCategory": "Fungicide",
    "notes": "Refer to product label for complete information",
    "manufacturer": "Check product label",
    "epaRegNum": "See product label",
    "epaLabelUrl": "Check EPA website",
    "moaName": "Multi-site chloronitrile",
    "moaDescription": "Multi-site enzyme and protein inactivation",
    "systemic": "Contact",
    "appType": "Foliar",
    "defaultRatePerGallon": null
  },
  {
    "id": "C036",
    "name": "Daconil",
    "category": "Fungicide",
    "type": "Concentrate",
    "actives": "Chlorothalonil",
    "moa": "M5",
    "rei": "12.0",
    "mixRate": "See product label",
    "targetSpectrum": "Leaf spots / powdery mildew / rust",
    "targetTypes": "Fungal disease complex",
    "allowedSites": "See product label",
    "restrictions": "Follow all label instructions and local regulations",
    "ipmCategory": "Fungicide",
    "notes": "Refer to product label for complete information",
    "manufacturer": "Check product label",
    "epaRegNum": "See product label",
    "epaLabelUrl": "Check EPA website",
    "moaName": "Multi-site chloronitrile",
    "moaDescription": "Multi-site enzyme and protein inactivation",
    "systemic": "Contact",
    "appType": "Foliar",
    "defaultRatePerGallon": null
  },
  {
    "id": "C037",
    "name": "Pillar SC Intrinsic",
    "category": "Fungicide",
    "type": "Concentrate",
    "actives": "Triticonazole + Pyraclostrobin",
    "moa": "3+11",
    "rei": "12.0",
    "mixRate": "See product label",
    "targetSpectrum": "Leaf spots / powdery mildew / rust",
    "targetTypes": "Fungal disease complex",
    "allowedSites": "See product label",
    "restrictions": "Follow all label instructions and local regulations",
    "ipmCategory": "Fungicide",
    "notes": "Refer to product label for complete information",
    "manufacturer": "Check product label",
    "epaRegNum": "See product label",
    "epaLabelUrl": "Check EPA website",
    "moaName": "DMI + QoI",
    "moaDescription": "Sterol biosynthesis inhibitor plus respiration inhibitor",
    "systemic": "Systemic",
    "appType": "Foliar",
    "defaultRatePerGallon": null
  },
  {
    "id": "C038",
    "name": "Avelyo",
    "category": "Fungicide",
    "type": "Concentrate",
    "actives": "Mefentrifluconazole",
    "moa": "3",
    "rei": "12.0",
    "mixRate": "See product label",
    "targetSpectrum": "Leaf spots / powdery mildew / rust, Root and crown rots (Fusarium, Rhizoctonia, Cylindrocladium, Thielaviopsis)",
    "targetTypes": "Fungal disease complex, Soil-borne fungi",
    "allowedSites": "See product label",
    "restrictions": "Follow all label instructions and local regulations",
    "ipmCategory": "Fungicide",
    "notes": "Refer to product label for complete information",
    "manufacturer": "Check product label",
    "epaRegNum": "See product label",
    "epaLabelUrl": "Check EPA website",
    "moaName": "DMI",
    "moaDescription": "Demethylation inhibitor in sterol biosynthesis pathway",
    "systemic": "Systemic",
    "appType": "Foliar",
    "defaultRatePerGallon": null
  },
  {
    "id": "C039",
    "name": "Segovis",
    "category": "Fungicide",
    "type": "Concentrate",
    "actives": "Oxathiapiprolin",
    "moa": "49",
    "rei": "4.0",
    "mixRate": "See product label",
    "targetSpectrum": "Downy mildew, Phytophthora diseases",
    "targetTypes": "Oomycete disease",
    "allowedSites": "See product label",
    "restrictions": "Follow all label instructions and local regulations",
    "ipmCategory": "Fungicide",
    "notes": "Refer to product label for complete information",
    "manufacturer": "Check product label",
    "epaRegNum": "See product label",
    "epaLabelUrl": "Check EPA website",
    "moaName": "OSBPI",
    "moaDescription": "Oxysterol-binding protein-related inhibition; extremely active on oomycetes",
    "systemic": "Systemic",
    "appType": "Foliar/Drench",
    "defaultRatePerGallon": null
  },
  {
    "id": "C040",
    "name": "Stature SC",
    "category": "Fungicide",
    "type": "Concentrate",
    "actives": "Dimethomorph",
    "moa": "40",
    "rei": "12.0",
    "mixRate": "See product label",
    "targetSpectrum": "Downy mildew",
    "targetTypes": "Oomycete disease",
    "allowedSites": "See product label",
    "restrictions": "Follow all label instructions and local regulations",
    "ipmCategory": "Fungicide",
    "notes": "Refer to product label for complete information",
    "manufacturer": "Check product label",
    "epaRegNum": "See product label",
    "epaLabelUrl": "Check EPA website",
    "moaName": "CAA",
    "moaDescription": "Cellulose synthesis inhibitor in oomycete cell walls",
    "systemic": "Systemic",
    "appType": "Foliar",
    "defaultRatePerGallon": null
  },
  {
    "id": "C041",
    "name": "Orvego",
    "category": "Fungicide",
    "type": "Concentrate",
    "actives": "Ametoctradin + Dimethomorph",
    "moa": "45+40",
    "rei": "12.0",
    "mixRate": "See product label",
    "targetSpectrum": "Downy mildew, Phytophthora diseases",
    "targetTypes": "Oomycete disease",
    "allowedSites": "See product label",
    "restrictions": "Follow all label instructions and local regulations",
    "ipmCategory": "Fungicide",
    "notes": "Refer to product label for complete information",
    "manufacturer": "Check product label",
    "epaRegNum": "See product label",
    "epaLabelUrl": "Check EPA website",
    "moaName": "QoSI + CAA",
    "moaDescription": "Respiration inhibition at Complex III plus cellulose synth inhibition",
    "systemic": "Systemic",
    "appType": "Foliar",
    "defaultRatePerGallon": null
  },
  {
    "id": "C042",
    "name": "Adorn",
    "category": "Fungicide",
    "type": "Concentrate",
    "actives": "Fluopicolide",
    "moa": "43",
    "rei": "12.0",
    "mixRate": "See product label",
    "targetSpectrum": "Downy mildew / Pythium",
    "targetTypes": "Oomycete disease",
    "allowedSites": "See product label",
    "restrictions": "Follow all label instructions and local regulations",
    "ipmCategory": "Fungicide",
    "notes": "Refer to product label for complete information",
    "manufacturer": "Check product label",
    "epaRegNum": "See product label",
    "epaLabelUrl": "Check EPA website",
    "moaName": "Benzamide",
    "moaDescription": "Disrupts spectrin-like proteins in oomycete cytoskeleton",
    "systemic": "Systemic",
    "appType": "Foliar/Drench",
    "defaultRatePerGallon": null
  },
  {
    "id": "C043",
    "name": "Empress Intrinsic",
    "category": "Fungicide",
    "type": "Concentrate",
    "actives": "Pyraclostrobin",
    "moa": "11",
    "rei": "12.0",
    "mixRate": "See product label",
    "targetSpectrum": "Pythium root rot",
    "targetTypes": "Oomycete disease",
    "allowedSites": "See product label",
    "restrictions": "Follow all label instructions and local regulations",
    "ipmCategory": "Fungicide",
    "notes": "Refer to product label for complete information",
    "manufacturer": "Check product label",
    "epaRegNum": "See product label",
    "epaLabelUrl": "Check EPA website",
    "moaName": "QoI",
    "moaDescription": "Blocks mitochondrial respiration at Qo site",
    "systemic": "Systemic",
    "appType": "Drench/Foliar",
    "defaultRatePerGallon": null
  },
  {
    "id": "C044",
    "name": "Segway O",
    "category": "Fungicide",
    "type": "Concentrate",
    "actives": "Cyazofamid",
    "moa": "21",
    "rei": "12.0",
    "mixRate": "See product label",
    "targetSpectrum": "Pythium root rot",
    "targetTypes": "Oomycete disease",
    "allowedSites": "See product label",
    "restrictions": "Follow all label instructions and local regulations",
    "ipmCategory": "Fungicide",
    "notes": "Refer to product label for complete information",
    "manufacturer": "Check product label",
    "epaRegNum": "See product label",
    "epaLabelUrl": "Check EPA website",
    "moaName": "QiI",
    "moaDescription": "Respiration inhibitor at Qi site of Complex III",
    "systemic": "Systemic",
    "appType": "Drench",
    "defaultRatePerGallon": null
  },
  {
    "id": "C045",
    "name": "Terrazole / Truban",
    "category": "Fungicide",
    "type": "Concentrate",
    "actives": "Etridiazole",
    "moa": "14",
    "rei": "12.0",
    "mixRate": "See product label",
    "targetSpectrum": "Pythium root rot",
    "targetTypes": "Oomycete disease",
    "allowedSites": "See product label",
    "restrictions": "Follow all label instructions and local regulations",
    "ipmCategory": "Fungicide",
    "notes": "Refer to product label for complete information",
    "manufacturer": "Check product label",
    "epaRegNum": "See product label",
    "epaLabelUrl": "Check EPA website",
    "moaName": "Aromatic hydrocarbon",
    "moaDescription": "Disrupts membrane lipids; affects cell membranes",
    "systemic": "Contact",
    "appType": "Drench",
    "defaultRatePerGallon": null
  },
  {
    "id": "C046",
    "name": "Subdue Maxx",
    "category": "Fungicide",
    "type": "Concentrate",
    "actives": "Mefenoxam",
    "moa": "4",
    "rei": "48.0",
    "mixRate": "See product label",
    "targetSpectrum": "Pythium / Phytophthora",
    "targetTypes": "Oomycete disease",
    "allowedSites": "See product label",
    "restrictions": "Follow all label instructions and local regulations",
    "ipmCategory": "Fungicide",
    "notes": "Refer to product label for complete information",
    "manufacturer": "Check product label",
    "epaRegNum": "See product label",
    "epaLabelUrl": "Check EPA website",
    "moaName": "Phenylamide",
    "moaDescription": "Inhibits rRNA synthesis; highly systemic",
    "systemic": "Systemic",
    "appType": "Drench",
    "defaultRatePerGallon": null
  },
  {
    "id": "C047",
    "name": "Aliette",
    "category": "Fungicide",
    "type": "Concentrate",
    "actives": "Fosetyl-Al",
    "moa": "P07",
    "rei": "12.0",
    "mixRate": "See product label",
    "targetSpectrum": "Phytophthora diseases",
    "targetTypes": "Oomycete disease",
    "allowedSites": "See product label",
    "restrictions": "Follow all label instructions and local regulations",
    "ipmCategory": "Fungicide",
    "notes": "Refer to product label for complete information",
    "manufacturer": "Check product label",
    "epaRegNum": "See product label",
    "epaLabelUrl": "Check EPA website",
    "moaName": "Phosphonate",
    "moaDescription": "Systemic phosphonate that induces plant defenses and suppresses oomycetes",
    "systemic": "Systemic",
    "appType": "Drench/Foliar",
    "defaultRatePerGallon": null
  },
  {
    "id": "C048",
    "name": "Medallion",
    "category": "Fungicide",
    "type": "Concentrate",
    "actives": "Fludioxonil",
    "moa": "12",
    "rei": "12.0",
    "mixRate": "See product label",
    "targetSpectrum": "Root and crown rots (Fusarium, Rhizoctonia, Cylindrocladium, Thielaviopsis)",
    "targetTypes": "Soil-borne fungi",
    "allowedSites": "See product label",
    "restrictions": "Follow all label instructions and local regulations",
    "ipmCategory": "Fungicide",
    "notes": "Refer to product label for complete information",
    "manufacturer": "Check product label",
    "epaRegNum": "See product label",
    "epaLabelUrl": "Check EPA website",
    "moaName": "Phenylpyrrole",
    "moaDescription": "Disrupts osmotic signal transduction",
    "systemic": "Contact",
    "appType": "Soil/Foliar",
    "defaultRatePerGallon": null
  },
  {
    "id": "C049",
    "name": "Phyton 27",
    "category": "Fungicide",
    "type": "Concentrate",
    "actives": "Copper sulfate complex",
    "moa": "M1",
    "rei": "48.0",
    "mixRate": "See product label",
    "targetSpectrum": "Bacterial diseases",
    "targetTypes": "Bacterial disease complex",
    "allowedSites": "See product label",
    "restrictions": "Follow all label instructions and local regulations",
    "ipmCategory": "Fungicide",
    "notes": "Refer to product label for complete information",
    "manufacturer": "Check product label",
    "epaRegNum": "See product label",
    "epaLabelUrl": "Check EPA website",
    "moaName": "Copper multi-site",
    "moaDescription": "Multi-site protein denaturation and enzyme disruption",
    "systemic": "Systemic/Contact",
    "appType": "Foliar",
    "defaultRatePerGallon": null
  },
  {
    "id": "C050",
    "name": "Camelot O",
    "category": "Fungicide",
    "type": "Concentrate",
    "actives": "Copper octanoate",
    "moa": "M1",
    "rei": "48.0",
    "mixRate": "See product label",
    "targetSpectrum": "Bacterial diseases",
    "targetTypes": "Bacterial disease complex",
    "allowedSites": "See product label",
    "restrictions": "Follow all label instructions and local regulations",
    "ipmCategory": "Fungicide",
    "notes": "Refer to product label for complete information",
    "manufacturer": "Check product label",
    "epaRegNum": "See product label",
    "epaLabelUrl": "Check EPA website",
    "moaName": "Copper multi-site",
    "moaDescription": "Multi-site protein denaturation",
    "systemic": "Contact",
    "appType": "Foliar",
    "defaultRatePerGallon": null
  },
  {
    "id": "C051",
    "name": "Grotto",
    "category": "Fungicide",
    "type": "Concentrate",
    "actives": "Copper salts",
    "moa": "M1",
    "rei": "48.0",
    "mixRate": "See product label",
    "targetSpectrum": "Bacterial diseases",
    "targetTypes": "Bacterial disease complex",
    "allowedSites": "See product label",
    "restrictions": "Follow all label instructions and local regulations",
    "ipmCategory": "Fungicide",
    "notes": "Refer to product label for complete information",
    "manufacturer": "Check product label",
    "epaRegNum": "See product label",
    "epaLabelUrl": "Check EPA website",
    "moaName": "Copper multi-site",
    "moaDescription": "Multi-site protein denaturation",
    "systemic": "Contact",
    "appType": "Foliar",
    "defaultRatePerGallon": null
  },
  {
    "id": "C052",
    "name": "Triathlon BA",
    "category": "Fungicide",
    "type": "Concentrate",
    "actives": "Bacillus amyloliquefaciens D747",
    "moa": "BM02",
    "rei": "4.0",
    "mixRate": "See product label",
    "targetSpectrum": "Bacterial diseases",
    "targetTypes": "Bacterial disease complex",
    "allowedSites": "See product label",
    "restrictions": "Follow all label instructions and local regulations",
    "ipmCategory": "Fungicide",
    "notes": "Refer to product label for complete information",
    "manufacturer": "Check product label",
    "epaRegNum": "See product label",
    "epaLabelUrl": "Check EPA website",
    "moaName": "Biofungicide",
    "moaDescription": "Produces antibiotics and induces plant resistance",
    "systemic": "Biological",
    "appType": "Foliar/Soil",
    "defaultRatePerGallon": null
  },
  {
    "id": "C053",
    "name": "Junction",
    "category": "Fungicide",
    "type": "Concentrate",
    "actives": "Mancozeb + Copper hydroxide",
    "moa": "M3+M1",
    "rei": "24.0",
    "mixRate": "See product label",
    "targetSpectrum": "Bacterial diseases",
    "targetTypes": "Bacterial disease complex",
    "allowedSites": "See product label",
    "restrictions": "Follow all label instructions and local regulations",
    "ipmCategory": "Fungicide",
    "notes": "Refer to product label for complete information",
    "manufacturer": "Check product label",
    "epaRegNum": "See product label",
    "epaLabelUrl": "Check EPA website",
    "moaName": "Dithiocarbamate + copper multi-site",
    "moaDescription": "Multi-site protectant mixture",
    "systemic": "Contact",
    "appType": "Foliar",
    "defaultRatePerGallon": null
  },
  {
    "id": "C054",
    "name": "Ventigra",
    "category": "Insecticide",
    "type": "Concentrate",
    "actives": "Afidopyropen",
    "moa": "9D",
    "rei": "4.0",
    "mixRate": "See product label",
    "targetSpectrum": "Aphids, Mealybugs, Scale (soft & hard), Whiteflies",
    "targetTypes": "Insect (scale), Insect (sucking)",
    "allowedSites": "See product label",
    "restrictions": "Follow all label instructions and local regulations",
    "ipmCategory": "Insecticide",
    "notes": "Refer to product label for complete information",
    "manufacturer": "Check product label",
    "epaRegNum": "See product label",
    "epaLabelUrl": "Check EPA website",
    "moaName": "Chordotonal organ modulator",
    "moaDescription": "Disrupts stretch receptor organs; rapid feeding cessation",
    "systemic": "Systemic",
    "appType": "Foliar",
    "defaultRatePerGallon": null
  },
  {
    "id": "C055",
    "name": "Velifer",
    "category": "Insecticide",
    "type": "Concentrate",
    "actives": "Beauveria bassiana strain PPRI 5339",
    "moa": "NC",
    "rei": "12.0",
    "mixRate": "See product label",
    "targetSpectrum": "Aphids",
    "targetTypes": "Insect (sucking)",
    "allowedSites": "See product label",
    "restrictions": "Follow all label instructions and local regulations",
    "ipmCategory": "Insecticide",
    "notes": "Refer to product label for complete information",
    "manufacturer": "Check product label",
    "epaRegNum": "See product label",
    "epaLabelUrl": "Check EPA website",
    "moaName": "Biological fungus",
    "moaDescription": "Entomopathogenic fungus infecting insects via cuticle",
    "systemic": "Biological",
    "appType": "Foliar",
    "defaultRatePerGallon": null
  },
  {
    "id": "C056",
    "name": "Safari",
    "category": "Insecticide",
    "type": "Concentrate",
    "actives": "Dinotefuran",
    "moa": "4A",
    "rei": "12.0",
    "mixRate": "See product label",
    "targetSpectrum": "Aphids, Fungus gnat larvae, Mealybugs",
    "targetTypes": "Insect (fly larva), Insect (sucking)",
    "allowedSites": "See product label",
    "restrictions": "Follow all label instructions and local regulations",
    "ipmCategory": "Insecticide",
    "notes": "Refer to product label for complete information",
    "manufacturer": "Check product label",
    "epaRegNum": "See product label",
    "epaLabelUrl": "Check EPA website",
    "moaName": "Neonicotinoid",
    "moaDescription": "Nicotinic acetylcholine receptor modulator; systemic",
    "systemic": "Systemic",
    "appType": "Drench, Drench/Foliar, Soil/Foliar",
    "defaultRatePerGallon": null
  },
  {
    "id": "C057",
    "name": "Pradia",
    "category": "Insecticide",
    "type": "Concentrate",
    "actives": "Cyantraniliprole + Flonicamid",
    "moa": "28+29",
    "rei": "12.0",
    "mixRate": "See product label",
    "targetSpectrum": "Aphids",
    "targetTypes": "Insect (sucking)",
    "allowedSites": "See product label",
    "restrictions": "Follow all label instructions and local regulations",
    "ipmCategory": "Insecticide",
    "notes": "Refer to product label for complete information",
    "manufacturer": "Check product label",
    "epaRegNum": "See product label",
    "epaLabelUrl": "Check EPA website",
    "moaName": "Diamide + feeding blocker",
    "moaDescription": "Ryanodine receptor activator plus chordotonal organ modulator",
    "systemic": "Systemic",
    "appType": "Foliar",
    "defaultRatePerGallon": null
  },
  {
    "id": "C058",
    "name": "XXpire",
    "category": "Insecticide",
    "type": "Concentrate",
    "actives": "Spinetoram + Sulfoxaflor",
    "moa": "5+4C",
    "rei": "12.0",
    "mixRate": "See product label",
    "targetSpectrum": "Aphids, Thrips",
    "targetTypes": "Insect (sucking), Insect (thysanoptera)",
    "allowedSites": "See product label",
    "restrictions": "Follow all label instructions and local regulations",
    "ipmCategory": "Insecticide",
    "notes": "Refer to product label for complete information",
    "manufacturer": "Check product label",
    "epaRegNum": "See product label",
    "epaLabelUrl": "Check EPA website",
    "moaName": "Spinosyn + butenolide",
    "moaDescription": "Dual nicotinic acetylcholine receptor modulation",
    "systemic": "Systemic",
    "appType": "Foliar",
    "defaultRatePerGallon": null
  },
  {
    "id": "C059",
    "name": "Azatin O",
    "category": "Insecticide",
    "type": "Concentrate",
    "actives": "Azadirachtin",
    "moa": "UN",
    "rei": "4.0",
    "mixRate": "See product label",
    "targetSpectrum": "Aphids",
    "targetTypes": "Insect (sucking)",
    "allowedSites": "See product label",
    "restrictions": "Follow all label instructions and local regulations",
    "ipmCategory": "Insecticide",
    "notes": "Refer to product label for complete information",
    "manufacturer": "Check product label",
    "epaRegNum": "See product label",
    "epaLabelUrl": "Check EPA website",
    "moaName": "Growth regulator (neem)",
    "moaDescription": "Interferes with molting hormones and feeding",
    "systemic": "Biological",
    "appType": "Foliar",
    "defaultRatePerGallon": null
  },
  {
    "id": "C060",
    "name": "Pylon",
    "category": "Miticide",
    "type": "Concentrate",
    "actives": "Chlorfenapyr",
    "moa": "13",
    "rei": "12.0",
    "mixRate": "See product label",
    "targetSpectrum": "Broad mites, Thrips",
    "targetTypes": "Insect (thysanoptera), Mite",
    "allowedSites": "See product label",
    "restrictions": "Follow all label instructions and local regulations",
    "ipmCategory": "Insecticide, Miticide",
    "notes": "Refer to product label for complete information",
    "manufacturer": "Check product label",
    "epaRegNum": "See product label",
    "epaLabelUrl": "Check EPA website",
    "moaName": "Oxidative phosphorylation uncoupler",
    "moaDescription": "Disrupts ATP production in mitochondria",
    "systemic": "Translaminar",
    "appType": "Foliar",
    "defaultRatePerGallon": null
  },
  {
    "id": "C061",
    "name": "Sanmite",
    "category": "Miticide",
    "type": "Concentrate",
    "actives": "Pyridaben",
    "moa": "21A",
    "rei": "12.0",
    "mixRate": "See product label",
    "targetSpectrum": "Broad mites",
    "targetTypes": "Mite",
    "allowedSites": "See product label",
    "restrictions": "Follow all label instructions and local regulations",
    "ipmCategory": "Miticide",
    "notes": "Refer to product label for complete information",
    "manufacturer": "Check product label",
    "epaRegNum": "See product label",
    "epaLabelUrl": "Check EPA website",
    "moaName": "ETC inhibitor",
    "moaDescription": "Blocks mitochondrial electron transport at Complex I",
    "systemic": "Contact",
    "appType": "Foliar",
    "defaultRatePerGallon": null
  },
  {
    "id": "C062",
    "name": "Sirocco",
    "category": "Miticide",
    "type": "Concentrate",
    "actives": "Bifenazate + Abamectin",
    "moa": "20D+6",
    "rei": "12.0",
    "mixRate": "See product label",
    "targetSpectrum": "Broad mites",
    "targetTypes": "Mite",
    "allowedSites": "See product label",
    "restrictions": "Follow all label instructions and local regulations",
    "ipmCategory": "Miticide",
    "notes": "Refer to product label for complete information",
    "manufacturer": "Check product label",
    "epaRegNum": "See product label",
    "epaLabelUrl": "Check EPA website",
    "moaName": "ETC inhibitor + GABA activator",
    "moaDescription": "Complex III inhibitor plus chloride channel activation",
    "systemic": "Contact/Translaminar",
    "appType": "Foliar",
    "defaultRatePerGallon": null
  },
  {
    "id": "C063",
    "name": "Sultan",
    "category": "Miticide",
    "type": "Concentrate",
    "actives": "Cyflumetofen",
    "moa": "25",
    "rei": "12.0",
    "mixRate": "See product label",
    "targetSpectrum": "Spider mites (twospotted)",
    "targetTypes": "Mite",
    "allowedSites": "See product label",
    "restrictions": "Follow all label instructions and local regulations",
    "ipmCategory": "Miticide",
    "notes": "Refer to product label for complete information",
    "manufacturer": "Check product label",
    "epaRegNum": "See product label",
    "epaLabelUrl": "Check EPA website",
    "moaName": "Complex II inhibitor",
    "moaDescription": "Inhibits mitochondrial succinate dehydrogenase in mites",
    "systemic": "Contact/Translaminar",
    "appType": "Foliar",
    "defaultRatePerGallon": null
  },
  {
    "id": "C064",
    "name": "Floramite",
    "category": "Miticide",
    "type": "Concentrate",
    "actives": "Bifenazate",
    "moa": "20D",
    "rei": "12.0",
    "mixRate": "See product label",
    "targetSpectrum": "Spider mites (twospotted)",
    "targetTypes": "Mite",
    "allowedSites": "See product label",
    "restrictions": "Follow all label instructions and local regulations",
    "ipmCategory": "Miticide",
    "notes": "Refer to product label for complete information",
    "manufacturer": "Check product label",
    "epaRegNum": "See product label",
    "epaLabelUrl": "Check EPA website",
    "moaName": "ETC inhibitor",
    "moaDescription": "Mitochondrial Complex III inhibitor",
    "systemic": "Contact",
    "appType": "Foliar",
    "defaultRatePerGallon": null
  },
  {
    "id": "C065",
    "name": "Avid",
    "category": "Miticide",
    "type": "Concentrate",
    "actives": "Abamectin",
    "moa": "6",
    "rei": "12.0",
    "mixRate": "See product label",
    "targetSpectrum": "Leafminers, Spider mites (twospotted)",
    "targetTypes": "Insect (leafminer), Mite",
    "allowedSites": "See product label",
    "restrictions": "Follow all label instructions and local regulations",
    "ipmCategory": "Insecticide, Miticide",
    "notes": "Refer to product label for complete information",
    "manufacturer": "Check product label",
    "epaRegNum": "See product label",
    "epaLabelUrl": "Check EPA website",
    "moaName": "GABA activator",
    "moaDescription": "Chloride channel activator; ingestion/contact action",
    "systemic": "Translaminar",
    "appType": "Foliar",
    "defaultRatePerGallon": null
  },
  {
    "id": "C067",
    "name": "Mainspring",
    "category": "Insecticide",
    "type": "Concentrate",
    "actives": "Cyantraniliprole",
    "moa": "28",
    "rei": "4.0",
    "mixRate": "See product label",
    "targetSpectrum": "Caterpillars, Thrips",
    "targetTypes": "Insect (chewing), Insect (thysanoptera)",
    "allowedSites": "See product label",
    "restrictions": "Follow all label instructions and local regulations",
    "ipmCategory": "Insecticide",
    "notes": "Refer to product label for complete information",
    "manufacturer": "Check product label",
    "epaRegNum": "See product label",
    "epaLabelUrl": "Check EPA website",
    "moaName": "Diamide",
    "moaDescription": "Ryanodine receptor activator",
    "systemic": "Systemic",
    "appType": "Foliar/Systemic",
    "defaultRatePerGallon": null
  },
  {
    "id": "C069",
    "name": "Aria",
    "category": "Insecticide",
    "type": "Concentrate",
    "actives": "Flonicamid",
    "moa": "29",
    "rei": "12.0",
    "mixRate": "See product label",
    "targetSpectrum": "Whiteflies",
    "targetTypes": "Insect (sucking)",
    "allowedSites": "See product label",
    "restrictions": "Follow all label instructions and local regulations",
    "ipmCategory": "Insecticide",
    "notes": "Refer to product label for complete information",
    "manufacturer": "Check product label",
    "epaRegNum": "See product label",
    "epaLabelUrl": "Check EPA website",
    "moaName": "Chordotonal modulator",
    "moaDescription": "Selective feeding blocker",
    "systemic": "Systemic",
    "appType": "Foliar",
    "defaultRatePerGallon": null
  },
  {
    "id": "C070",
    "name": "Altus",
    "category": "Insecticide",
    "type": "Concentrate",
    "actives": "Flupyradifurone",
    "moa": "4D",
    "rei": "4.0",
    "mixRate": "See product label",
    "targetSpectrum": "Whiteflies",
    "targetTypes": "Insect (sucking)",
    "allowedSites": "See product label",
    "restrictions": "Follow all label instructions and local regulations",
    "ipmCategory": "Insecticide",
    "notes": "Refer to product label for complete information",
    "manufacturer": "Check product label",
    "epaRegNum": "See product label",
    "epaLabelUrl": "Check EPA website",
    "moaName": "Butenolide",
    "moaDescription": "Nicotinic acetylcholine receptor modulator; systemic",
    "systemic": "Systemic",
    "appType": "Foliar/Drench",
    "defaultRatePerGallon": null
  },
  {
    "id": "C071",
    "name": "Ultra-Pure Oil",
    "category": "Insecticide",
    "type": "Concentrate",
    "actives": "Highly refined mineral oil",
    "moa": "NC",
    "rei": "4.0",
    "mixRate": "See product label",
    "targetSpectrum": "Mealybugs, Scale (soft & hard), Whiteflies",
    "targetTypes": "Insect (scale), Insect (sucking)",
    "allowedSites": "See product label",
    "restrictions": "Follow all label instructions and local regulations",
    "ipmCategory": "Insecticide",
    "notes": "Refer to product label for complete information",
    "manufacturer": "Check product label",
    "epaRegNum": "See product label",
    "epaLabelUrl": "Check EPA website",
    "moaName": "Suffocating oil",
    "moaDescription": "Smothers immature stages and eggs",
    "systemic": "Contact, Contact/Biological-like",
    "appType": "Foliar",
    "defaultRatePerGallon": null
  },
  {
    "id": "C072",
    "name": "Gnatrol",
    "category": "Insecticide",
    "type": "Concentrate",
    "actives": "Bacillus thuringiensis israelensis",
    "moa": "11A",
    "rei": "4.0",
    "mixRate": "See product label",
    "targetSpectrum": "Fungus gnat larvae",
    "targetTypes": "Insect (fly larva)",
    "allowedSites": "See product label",
    "restrictions": "Follow all label instructions and local regulations",
    "ipmCategory": "Insecticide",
    "notes": "Refer to product label for complete information",
    "manufacturer": "Check product label",
    "epaRegNum": "See product label",
    "epaLabelUrl": "Check EPA website",
    "moaName": "Microbial stomach poison",
    "moaDescription": "Toxins disrupt larval midgut; larvae stop feeding",
    "systemic": "Biological",
    "appType": "Soil drench",
    "defaultRatePerGallon": null
  },
  {
    "id": "C073",
    "name": "Citation",
    "category": "Insecticide",
    "type": "Concentrate",
    "actives": "Cyromazine",
    "moa": "17",
    "rei": "12.0",
    "mixRate": "See product label",
    "targetSpectrum": "Fungus gnat larvae",
    "targetTypes": "Insect (fly larva)",
    "allowedSites": "See product label",
    "restrictions": "Follow all label instructions and local regulations",
    "ipmCategory": "Insecticide",
    "notes": "Refer to product label for complete information",
    "manufacturer": "Check product label",
    "epaRegNum": "See product label",
    "epaLabelUrl": "Check EPA website",
    "moaName": "Growth regulator",
    "moaDescription": "Affects larval development and pupation",
    "systemic": "Systemic",
    "appType": "Soil drench",
    "defaultRatePerGallon": null
  },
  {
    "id": "C074",
    "name": "Adept",
    "category": "Insecticide",
    "type": "Concentrate",
    "actives": "Diflubenzuron",
    "moa": "15",
    "rei": "12.0",
    "mixRate": "See product label",
    "targetSpectrum": "Fungus gnat larvae",
    "targetTypes": "Insect (fly larva)",
    "allowedSites": "See product label",
    "restrictions": "Follow all label instructions and local regulations",
    "ipmCategory": "Insecticide",
    "notes": "Refer to product label for complete information",
    "manufacturer": "Check product label",
    "epaRegNum": "See product label",
    "epaLabelUrl": "Check EPA website",
    "moaName": "Chitin synthesis inhibitor",
    "moaDescription": "Interferes with cuticle formation",
    "systemic": "Systemic",
    "appType": "Soil drench",
    "defaultRatePerGallon": null
  },
  {
    "id": "C075",
    "name": "Orthene 1300 TR / Precise",
    "category": "Insecticide",
    "type": "Concentrate",
    "actives": "Acephate",
    "moa": "1B",
    "rei": "24.0",
    "mixRate": "See product label",
    "targetSpectrum": "Scale (soft & hard)",
    "targetTypes": "Insect (scale)",
    "allowedSites": "See product label",
    "restrictions": "Follow all label instructions and local regulations",
    "ipmCategory": "Insecticide",
    "notes": "Refer to product label for complete information",
    "manufacturer": "Check product label",
    "epaRegNum": "See product label",
    "epaLabelUrl": "Check EPA website",
    "moaName": "AChE inhibitor",
    "moaDescription": "Organophosphate; inhibits acetylcholinesterase",
    "systemic": "Systemic",
    "appType": "Fogger/contact",
    "defaultRatePerGallon": null
  },
  {
    "id": "C076",
    "name": "Dipel",
    "category": "Insecticide",
    "type": "Concentrate",
    "actives": "Bacillus thuringiensis kurstaki",
    "moa": "11B",
    "rei": "4.0",
    "mixRate": "See product label",
    "targetSpectrum": "Caterpillars",
    "targetTypes": "Insect (chewing)",
    "allowedSites": "See product label",
    "restrictions": "Follow all label instructions and local regulations",
    "ipmCategory": "Insecticide",
    "notes": "Refer to product label for complete information",
    "manufacturer": "Check product label",
    "epaRegNum": "See product label",
    "epaLabelUrl": "Check EPA website",
    "moaName": "Microbial stomach poison",
    "moaDescription": "Bt toxins disrupt caterpillar midgut",
    "systemic": "Biological",
    "appType": "Foliar",
    "defaultRatePerGallon": null
  },
  {
    "id": "C077",
    "name": "Intrepid",
    "category": "Insecticide",
    "type": "Concentrate",
    "actives": "Methoxyfenozide",
    "moa": "18",
    "rei": "4.0",
    "mixRate": "See product label",
    "targetSpectrum": "Caterpillars",
    "targetTypes": "Insect (chewing)",
    "allowedSites": "See product label",
    "restrictions": "Follow all label instructions and local regulations",
    "ipmCategory": "Insecticide",
    "notes": "Refer to product label for complete information",
    "manufacturer": "Check product label",
    "epaRegNum": "See product label",
    "epaLabelUrl": "Check EPA website",
    "moaName": "Ecdysone agonist",
    "moaDescription": "Mimics molting hormone; larvae stop feeding",
    "systemic": "Systemic",
    "appType": "Foliar",
    "defaultRatePerGallon": null
  },
  {
    "id": "C078",
    "name": "Pedestal",
    "category": "Insecticide",
    "type": "Concentrate",
    "actives": "Novaluron",
    "moa": "15",
    "rei": "12.0",
    "mixRate": "See product label",
    "targetSpectrum": "Caterpillars",
    "targetTypes": "Insect (chewing)",
    "allowedSites": "See product label",
    "restrictions": "Follow all label instructions and local regulations",
    "ipmCategory": "Insecticide",
    "notes": "Refer to product label for complete information",
    "manufacturer": "Check product label",
    "epaRegNum": "See product label",
    "epaLabelUrl": "Check EPA website",
    "moaName": "Chitin synthesis inhibitor",
    "moaDescription": "Interferes with cuticle deposition",
    "systemic": "Systemic",
    "appType": "Foliar",
    "defaultRatePerGallon": null
  },
  {
    "id": "C079",
    "name": "TriStar",
    "category": "Insecticide",
    "type": "Concentrate",
    "actives": "Acetamiprid",
    "moa": "4A",
    "rei": "12.0",
    "mixRate": "See product label",
    "targetSpectrum": "Leafminers",
    "targetTypes": "Insect (leafminer)",
    "allowedSites": "See product label",
    "restrictions": "Follow all label instructions and local regulations",
    "ipmCategory": "Insecticide",
    "notes": "Refer to product label for complete information",
    "manufacturer": "Check product label",
    "epaRegNum": "See product label",
    "epaLabelUrl": "Check EPA website",
    "moaName": "Neonicotinoid",
    "moaDescription": "Nicotinic acetylcholine receptor modulator",
    "systemic": "Systemic",
    "appType": "Foliar",
    "defaultRatePerGallon": null
  },
  {
    "id": "C081",
    "name": "Sluggo",
    "category": "Insecticide",
    "type": "Concentrate",
    "actives": "Iron phosphate",
    "moa": "NC",
    "rei": "0.0",
    "mixRate": "See product label",
    "targetSpectrum": "Slugs and snails",
    "targetTypes": "Mollusc",
    "allowedSites": "See product label",
    "restrictions": "Follow all label instructions and local regulations",
    "ipmCategory": "Insecticide",
    "notes": "Refer to product label for complete information",
    "manufacturer": "Check product label",
    "epaRegNum": "See product label",
    "epaLabelUrl": "Check EPA website",
    "moaName": "Stomach poison",
    "moaDescription": "Disrupts calcium metabolism; snails stop feeding",
    "systemic": "Biological-like",
    "appType": "Bait",
    "defaultRatePerGallon": null
  },
  {
    "id": "C082",
    "name": "Dimension EW",
    "category": "Herbicide",
    "type": "Concentrate",
    "actives": "Dithiopyr",
    "moa": "3",
    "rei": "12.0",
    "mixRate": "See product label",
    "targetSpectrum": "Nursery weeds (grasses & some broadleaves)",
    "targetTypes": "Weeds",
    "allowedSites": "See product label",
    "restrictions": "Follow all label instructions and local regulations",
    "ipmCategory": "Herbicide",
    "notes": "Refer to product label for complete information",
    "manufacturer": "Check product label",
    "epaRegNum": "See product label",
    "epaLabelUrl": "Check EPA website",
    "moaName": "Mitosis inhibitor",
    "moaDescription": "Inhibits microtubule formation; pre-emergent root inhibition",
    "systemic": "Soil-residual",
    "appType": "Soil pre-emergent",
    "defaultRatePerGallon": null
  },
  {
    "id": "C083",
    "name": "Surflan AS",
    "category": "Herbicide",
    "type": "Concentrate",
    "actives": "Oryzalin",
    "moa": "3",
    "rei": "12.0",
    "mixRate": "See product label",
    "targetSpectrum": "Nursery weeds (grasses & some broadleaves)",
    "targetTypes": "Weeds",
    "allowedSites": "See product label",
    "restrictions": "Follow all label instructions and local regulations",
    "ipmCategory": "Herbicide",
    "notes": "Refer to product label for complete information",
    "manufacturer": "Check product label",
    "epaRegNum": "See product label",
    "epaLabelUrl": "Check EPA website",
    "moaName": "Dinitroaniline",
    "moaDescription": "Inhibits cell division at germination",
    "systemic": "Soil-residual",
    "appType": "Soil pre-emergent",
    "defaultRatePerGallon": null
  },
  {
    "id": "C084",
    "name": "Barricade / RegalKade",
    "category": "Herbicide",
    "type": "Concentrate",
    "actives": "Prodiamine",
    "moa": "3",
    "rei": "12.0",
    "mixRate": "See product label",
    "targetSpectrum": "Nursery weeds (grasses & some broadleaves)",
    "targetTypes": "Weeds",
    "allowedSites": "See product label",
    "restrictions": "Follow all label instructions and local regulations",
    "ipmCategory": "Herbicide",
    "notes": "Refer to product label for complete information",
    "manufacturer": "Check product label",
    "epaRegNum": "See product label",
    "epaLabelUrl": "Check EPA website",
    "moaName": "Dinitroaniline",
    "moaDescription": "Root/shoot inhibition at emergence",
    "systemic": "Soil-residual",
    "appType": "Soil pre-emergent",
    "defaultRatePerGallon": null
  },
  {
    "id": "C085",
    "name": "Broadstar G / SureGuard SC",
    "category": "Herbicide",
    "type": "Concentrate",
    "actives": "Flumioxazin",
    "moa": "14",
    "rei": "12.0",
    "mixRate": "See product label",
    "targetSpectrum": "Nursery weeds (broadleaves)",
    "targetTypes": "Weeds",
    "allowedSites": "See product label",
    "restrictions": "Follow all label instructions and local regulations",
    "ipmCategory": "Herbicide",
    "notes": "Refer to product label for complete information",
    "manufacturer": "Check product label",
    "epaRegNum": "See product label",
    "epaLabelUrl": "Check EPA website",
    "moaName": "PPO inhibitor",
    "moaDescription": "Protox inhibitor causing membrane disruption",
    "systemic": "Soil-residual",
    "appType": "Soil pre-emergent",
    "defaultRatePerGallon": null
  },
  {
    "id": "C086",
    "name": "Goal XL",
    "category": "Herbicide",
    "type": "Concentrate",
    "actives": "Oxyfluorfen",
    "moa": "14",
    "rei": "24.0",
    "mixRate": "See product label",
    "targetSpectrum": "Nursery weeds (broadleaves and some grasses)",
    "targetTypes": "Weeds",
    "allowedSites": "See product label",
    "restrictions": "Follow all label instructions and local regulations",
    "ipmCategory": "Herbicide",
    "notes": "Refer to product label for complete information",
    "manufacturer": "Check product label",
    "epaRegNum": "See product label",
    "epaLabelUrl": "Check EPA website",
    "moaName": "PPO inhibitor",
    "moaDescription": "Contact PPO inhibitor; primarily contact activity",
    "systemic": "Contact/Soil-residual",
    "appType": "Soil/Foliar (directed)",
    "defaultRatePerGallon": null
  },
  {
    "id": "C087",
    "name": "Tower EC",
    "category": "Herbicide",
    "type": "Concentrate",
    "actives": "Dimethenamid-P",
    "moa": "15",
    "rei": "24.0",
    "mixRate": "See product label",
    "targetSpectrum": "Nursery weeds (grasses/broadleaves/sedges)",
    "targetTypes": "Weeds",
    "allowedSites": "See product label",
    "restrictions": "Follow all label instructions and local regulations",
    "ipmCategory": "Herbicide",
    "notes": "Refer to product label for complete information",
    "manufacturer": "Check product label",
    "epaRegNum": "See product label",
    "epaLabelUrl": "Check EPA website",
    "moaName": "LCFA inhibitor",
    "moaDescription": "Inhibits very-long-chain fatty acid synthesis",
    "systemic": "Soil-residual",
    "appType": "Soil pre-emergent",
    "defaultRatePerGallon": null
  },
  {
    "id": "C088",
    "name": "Pennant Magnum",
    "category": "Herbicide",
    "type": "Concentrate",
    "actives": "S-metolachlor",
    "moa": "15",
    "rei": "24.0",
    "mixRate": "See product label",
    "targetSpectrum": "Nursery weeds (grasses/broadleaves/sedges)",
    "targetTypes": "Weeds",
    "allowedSites": "See product label",
    "restrictions": "Follow all label instructions and local regulations",
    "ipmCategory": "Herbicide",
    "notes": "Refer to product label for complete information",
    "manufacturer": "Check product label",
    "epaRegNum": "See product label",
    "epaLabelUrl": "Check EPA website",
    "moaName": "LCFA inhibitor",
    "moaDescription": "Interferes with seedling shoot development",
    "systemic": "Soil-residual",
    "appType": "Soil pre-emergent",
    "defaultRatePerGallon": null
  },
  {
    "id": "C089",
    "name": "Stricor EC",
    "category": "Herbicide",
    "type": "Concentrate",
    "actives": "Pethoxamid",
    "moa": "15",
    "rei": "24.0",
    "mixRate": "See product label",
    "targetSpectrum": "Nursery weeds (grasses/broadleaves/sedges)",
    "targetTypes": "Weeds",
    "allowedSites": "See product label",
    "restrictions": "Follow all label instructions and local regulations",
    "ipmCategory": "Herbicide",
    "notes": "Refer to product label for complete information",
    "manufacturer": "Check product label",
    "epaRegNum": "See product label",
    "epaLabelUrl": "Check EPA website",
    "moaName": "LCFA inhibitor",
    "moaDescription": "Similar to dimethenamid; pre-emergent activity",
    "systemic": "Soil-residual",
    "appType": "Soil pre-emergent",
    "defaultRatePerGallon": null
  },
  {
    "id": "C090",
    "name": "Gallery SC",
    "category": "Herbicide",
    "type": "Concentrate",
    "actives": "Isoxaben",
    "moa": "21",
    "rei": "12.0",
    "mixRate": "See product label",
    "targetSpectrum": "Nursery weeds (broadleaves)",
    "targetTypes": "Weeds",
    "allowedSites": "See product label",
    "restrictions": "Follow all label instructions and local regulations",
    "ipmCategory": "Herbicide",
    "notes": "Refer to product label for complete information",
    "manufacturer": "Check product label",
    "epaRegNum": "See product label",
    "epaLabelUrl": "Check EPA website",
    "moaName": "Cellulose inhibitor",
    "moaDescription": "Inhibits cellulose biosynthesis in roots/shoots",
    "systemic": "Soil-residual",
    "appType": "Soil pre-emergent",
    "defaultRatePerGallon": null
  },
  {
    "id": "C091",
    "name": "Snapshot G",
    "category": "Herbicide",
    "type": "Concentrate",
    "actives": "Isoxaben + Trifluralin",
    "moa": "21+3",
    "rei": "24.0",
    "mixRate": "See product label",
    "targetSpectrum": "Nursery weeds (broadleaves and some grasses)",
    "targetTypes": "Weeds",
    "allowedSites": "See product label",
    "restrictions": "Follow all label instructions and local regulations",
    "ipmCategory": "Herbicide",
    "notes": "Refer to product label for complete information",
    "manufacturer": "Check product label",
    "epaRegNum": "See product label",
    "epaLabelUrl": "Check EPA website",
    "moaName": "Cellulose inhibitor + dinitroaniline",
    "moaDescription": "Dual MoA pre-emergent broad-spectrum",
    "systemic": "Soil-residual",
    "appType": "Soil pre-emergent",
    "defaultRatePerGallon": null
  },
  {
    "id": "C092",
    "name": "Gemini SC/G",
    "category": "Herbicide",
    "type": "Concentrate",
    "actives": "Isoxaben + Prodiamine",
    "moa": "21+3",
    "rei": "24.0",
    "mixRate": "See product label",
    "targetSpectrum": "Nursery weeds (broadleaves and some grasses)",
    "targetTypes": "Weeds",
    "allowedSites": "See product label",
    "restrictions": "Follow all label instructions and local regulations",
    "ipmCategory": "Herbicide",
    "notes": "Refer to product label for complete information",
    "manufacturer": "Check product label",
    "epaRegNum": "See product label",
    "epaLabelUrl": "Check EPA website",
    "moaName": "Cellulose inhibitor + dinitroaniline",
    "moaDescription": "Container pre-emergent; good rotation partner",
    "systemic": "Soil-residual",
    "appType": "Soil pre-emergent",
    "defaultRatePerGallon": null
  },
  {
    "id": "C093",
    "name": "Fortress G",
    "category": "Herbicide",
    "type": "Concentrate",
    "actives": "Isoxaben + Dithiopyr",
    "moa": "21+3",
    "rei": "24.0",
    "mixRate": "See product label",
    "targetSpectrum": "Nursery weeds (broadleaves and some grasses)",
    "targetTypes": "Weeds",
    "allowedSites": "See product label",
    "restrictions": "Follow all label instructions and local regulations",
    "ipmCategory": "Herbicide",
    "notes": "Refer to product label for complete information",
    "manufacturer": "Check product label",
    "epaRegNum": "See product label",
    "epaLabelUrl": "Check EPA website",
    "moaName": "Cellulose inhibitor + mitosis inhibitor",
    "moaDescription": "Dual MoA pre-emergent mix",
    "systemic": "Soil-residual",
    "appType": "Soil pre-emergent",
    "defaultRatePerGallon": null
  },
  {
    "id": "C094",
    "name": "FreeHand 1.75G",
    "category": "Herbicide",
    "type": "Concentrate",
    "actives": "Dimethenamid-P + Pendimethalin",
    "moa": "15+3",
    "rei": "24.0",
    "mixRate": "See product label",
    "targetSpectrum": "Nursery weeds (broadleaves and grasses)",
    "targetTypes": "Weeds",
    "allowedSites": "See product label",
    "restrictions": "Follow all label instructions and local regulations",
    "ipmCategory": "Herbicide",
    "notes": "Refer to product label for complete information",
    "manufacturer": "Check product label",
    "epaRegNum": "See product label",
    "epaLabelUrl": "Check EPA website",
    "moaName": "LCFA inhibitor + dinitroaniline",
    "moaDescription": "Pre-emergent on grasses and broadleaves",
    "systemic": "Soil-residual",
    "appType": "Soil pre-emergent",
    "defaultRatePerGallon": null
  },
  {
    "id": "C095",
    "name": "Rout G",
    "category": "Herbicide",
    "type": "Concentrate",
    "actives": "Oxyfluorfen + Oryzalin",
    "moa": "14+3",
    "rei": "24.0",
    "mixRate": "See product label",
    "targetSpectrum": "Nursery weeds (broadleaves and grasses)",
    "targetTypes": "Weeds",
    "allowedSites": "See product label",
    "restrictions": "Follow all label instructions and local regulations",
    "ipmCategory": "Herbicide",
    "notes": "Refer to product label for complete information",
    "manufacturer": "Check product label",
    "epaRegNum": "See product label",
    "epaLabelUrl": "Check EPA website",
    "moaName": "PPO inhibitor + dinitroaniline",
    "moaDescription": "Pre-emergent combination; contact and residual",
    "systemic": "Soil-residual",
    "appType": "Soil pre-emergent",
    "defaultRatePerGallon": null
  },
  {
    "id": "C096",
    "name": "OH2 G",
    "category": "Herbicide",
    "type": "Concentrate",
    "actives": "Oxyfluorfen + Pendimethalin",
    "moa": "14+3",
    "rei": "24.0",
    "mixRate": "See product label",
    "targetSpectrum": "Nursery weeds (broadleaves and grasses)",
    "targetTypes": "Weeds",
    "allowedSites": "See product label",
    "restrictions": "Follow all label instructions and local regulations",
    "ipmCategory": "Herbicide",
    "notes": "Refer to product label for complete information",
    "manufacturer": "Check product label",
    "epaRegNum": "See product label",
    "epaLabelUrl": "Check EPA website",
    "moaName": "PPO inhibitor + dinitroaniline",
    "moaDescription": "Pre-emergent combo; some contact burn-down",
    "systemic": "Soil-residual",
    "appType": "Soil pre-emergent",
    "defaultRatePerGallon": null
  },
  {
    "id": "C097",
    "name": "Biathlon G",
    "category": "Herbicide",
    "type": "Concentrate",
    "actives": "Oxyfluorfen + Prodiamine",
    "moa": "14+3",
    "rei": "24.0",
    "mixRate": "See product label",
    "targetSpectrum": "Nursery weeds (broadleaves and grasses)",
    "targetTypes": "Weeds",
    "allowedSites": "See product label",
    "restrictions": "Follow all label instructions and local regulations",
    "ipmCategory": "Herbicide",
    "notes": "Refer to product label for complete information",
    "manufacturer": "Check product label",
    "epaRegNum": "See product label",
    "epaLabelUrl": "Check EPA website",
    "moaName": "PPO inhibitor + dinitroaniline",
    "moaDescription": "Granular pre-emergent with PPO and dinitroaniline MoAs",
    "systemic": "Soil-residual",
    "appType": "Soil pre-emergent",
    "defaultRatePerGallon": null
  },
  {
    "id": "C098",
    "name": "RegalStar G",
    "category": "Herbicide",
    "type": "Concentrate",
    "actives": "Oxadiazon + Prodiamine",
    "moa": "14+3",
    "rei": "24.0",
    "mixRate": "See product label",
    "targetSpectrum": "Nursery weeds (broadleaves and grasses)",
    "targetTypes": "Weeds",
    "allowedSites": "See product label",
    "restrictions": "Follow all label instructions and local regulations",
    "ipmCategory": "Herbicide",
    "notes": "Refer to product label for complete information",
    "manufacturer": "Check product label",
    "epaRegNum": "See product label",
    "epaLabelUrl": "Check EPA website",
    "moaName": "PPO inhibitor + dinitroaniline",
    "moaDescription": "Pre-emergent combo; ornamentals/turf labeled uses",
    "systemic": "Soil-residual",
    "appType": "Soil pre-emergent",
    "defaultRatePerGallon": null
  },
  {
    "id": "C099",
    "name": "Regal O-O G",
    "category": "Herbicide",
    "type": "Concentrate",
    "actives": "Oxyfluorfen + Oxadiazon",
    "moa": "14+14",
    "rei": "24.0",
    "mixRate": "See product label",
    "targetSpectrum": "Nursery weeds (broadleaves and grasses)",
    "targetTypes": "Weeds",
    "allowedSites": "See product label",
    "restrictions": "Follow all label instructions and local regulations",
    "ipmCategory": "Herbicide",
    "notes": "Refer to product label for complete information",
    "manufacturer": "Check product label",
    "epaRegNum": "See product label",
    "epaLabelUrl": "Check EPA website",
    "moaName": "Dual PPO inhibitors",
    "moaDescription": "Two PPO MoAs; use sparingly in rotation",
    "systemic": "Soil-residual",
    "appType": "Soil pre-emergent",
    "defaultRatePerGallon": null
  },
  {
    "id": "C100",
    "name": "SureGuard Xtra SC",
    "category": "Herbicide",
    "type": "Concentrate",
    "actives": "Flumioxazin + Pyroxasulfone",
    "moa": "14+15",
    "rei": "24.0",
    "mixRate": "See product label",
    "targetSpectrum": "Nursery weeds (broadleaves and grasses)",
    "targetTypes": "Weeds",
    "allowedSites": "See product label",
    "restrictions": "Follow all label instructions and local regulations",
    "ipmCategory": "Herbicide",
    "notes": "Refer to product label for complete information",
    "manufacturer": "Check product label",
    "epaRegNum": "See product label",
    "epaLabelUrl": "Check EPA website",
    "moaName": "PPO inhibitor + LCFA inhibitor",
    "moaDescription": "Pre-emergent control of broadleaves and grasses",
    "systemic": "Soil-residual",
    "appType": "Soil pre-emergent",
    "defaultRatePerGallon": null
  }
];

// Export to window for use by other scripts
if (typeof window !== 'undefined') {
  window.chemicals = chemicals;
}
